services:
  backend:
    build:
      context: ./orion.api
      dockerfile: Dockerfile
    container_name: orion-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: "mongodb+srv://usuario1:usuario1@cluster0.smpvu.mongodb.net/Orion?retryWrites=true&w=majority"
      JWT_SECRET: "super_secret_key_123"
      PORT: 5000

  frontend:
    build:
      context: ./orion.gui
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:5000/api"
    container_name: orion-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend